import Head from 'next/head';
import React, { useEffect, useState } from 'react';

// import Tmdb from '../src/components/database/Tmdb';
// import MovieRow from '../src/components/movie-row/MovieRow';


export default function MovieItem({info}) {
  
  
  
  
  
  return (
    <>
      <Head>
        <title>NextFlix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      <main>

        <div>
            Pagina sobre o filme:
            <hr/>
            Titulo {info.title}
            <p>
              Nota {info.vote_average}
            </p>
            <div>
              <img src={`http://image.tmdb.org/t/p/original${info.backdrop_path}`} width="400" />
            </div>

            <p>
              Descrição {info.overview}
            </p>

            <button>
                voltar para busca
            </button>
        </div>

      </main>
      
  


      <footer>
      </footer>
    </>
  );
}

//function for set server side mode page on
export async function getServerSideProps(context) {


    //variavel responsavel por pegar o ID do filme especifico
  const res = await fetch (`${apiBase}/movie/${context.params.id}?api_key=${apiKey}`);
  const json = await res.json();

  return{
    //retornando as informações de um filme especifico
    props:{
      info: json.info
    }
  }
}
