import Head from 'next/head';
import React, { useEffect, useState } from 'react';

// import Tmdb from '../src/components/database/Tmdb';
// import MovieRow from '../src/components/movie-row/MovieRow';


export default function Home({author}) {
  
  

  
  
  return (
    <>
      <Head>
        <title>NextFlix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      <main>

        <div>
            Blabla pagina estatica sobre o autor: {author}
        </div>




      </main>
      
  


      <footer>
      </footer>
    </>
  );
}

//function for set static page mode
export async function getStaticProps() {



  return{

    props:{
      author: 'guilhermemm-dev' 
    }

  }
}
