import Head from 'next/head';
import Link from 'next/link'
import React, { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'
// import Tmdb from '../src/components/database/Tmdb';

import dbApi from './api/dbApi'
import MovieRow from '../src/components/movie-row/MovieRow'

export default function Home({list}) {
  
  const [movieList, setMovieList] = useState([]);

  useEffect((  ) => {

    const loadAll = async () => {
    let list = await dbApi.getHomeList();
    setMovieList(list);



    }
    loadAll();
  }, []);
  
  
  
  
  
  return (
    <>
      <Head>
        <title>NextFlix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      <main>
      <div className="page">
          <section className="lists">
          {movieList.map( (item,key) => (

            <div>
              <MovieRow key={key} 
              
              title={item?.title} 
              items={item?.items}
            
              
              />
            </div>
          
          ))}
          </section>
          <div>
            

          <Link href="/search"><button>Buscaaaaaaaaa</button></Link>

            
          </div>
      <Link href="/about">Pagina Sobreee mimmm</Link>  
      </div>
      </main>
      
  


      <footer>
      </footer>
    </>
  );
}

//function for set server side render mode
export async function getServerSideProps() {

  const res = await fetch ('http://localhost:3000/api/trending');
  const json = await res.json();

  return{

    props:{
      list: json.list
    }

  }
}
