import Head from 'next/head'
import React, { useEffect, useState } from 'react'
// import Database from '../src/components/database/Database'
// import MovieRow from '../src/components/movie-row/MovieRow'


export default function Home() {
  
  
  
  
  
  
  
  
  
  
  return (
    <>
      <Head>
        <title>NextFlix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      
      <div className="page">
          <section className="lists">
          blablablasectionlists
          </section>
      </div>
      
      
      
      
      
     


    






      <footer>
      </footer>
    </>
  )
}
